# config/database.yml

default: &default
  adapter: sqlserver
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: sa 
  password: P@ssw0rd123

development:
  <<: *default
  database: rubiks_development

test:
  <<: *default
  database: rubiks_test

production:
  <<: *default
  database: rubiks_production
  username: sa
  password: <%= ENV["DB_PASSWORD"] %>
  host: your_production_host